### ISSUE TITLE
CloverWindows.bat CMD not working 

### ISSUE THREAD

**Issue by Kindgentlemanthatisntkind** [ryanrudolfoba/SteamDeck-Clover-dualboot#1]
When I run CloverWindows as administrator it says that "the system can't find the file specified."
and "invalid argument/option - 'blahblahblah\CloverTask.xml"
![20230113_213126_HDR](https://user-images.githubusercontent.com/122226421/212413642-db5ebaa3-42a3-4a80-9d19-089b26b193e9.jpg)
Any help?

**Comment by ryanrudolfoba** [comment]
Did you download the ZIP file?

Please refer to this video tutorial

https://m.youtube.com/watch?v=5ITV_9_ny24&feature=youtu.be

**Comment by Kindgentlemanthatisntkind** [comment]
Yeah I extracted the zip, but I can't seem to find device lockdown in windows features.

**Comment by ryanrudolfoba** [comment]
> 

Please skip the Unbranded Boot / Device Lockdown.

I've updated the README you dont need that anymore. But instead use this -


Open command prompt with admin privileges and enter the command -
bcdedit.exe -set {globalsettings} highestmode on

**Comment by Kindgentlemanthatisntkind** [comment]
![Screenshot 2023-01-15 002704](https://user-images.githubusercontent.com/122226421/212503094-11ac9a6c-badb-4136-8b41-7ccd0fa03683.png)
I did that and still the same thing happened. Do you need any info about my device? I can give you some if you want.

**Comment by ryanrudolfoba** [comment]
OK i tried to automate the creation of the Scheduled Task so it is less painful, but for some reason it doesnt work on your machine.

Please create the Scheduled Task manually instead -

1. Create a folder called C:\1Clover-tools
2. Copy CloverTask.ps1 to C:\1Clover-tools
3. Go to Task Scheduler > Task Scheduler Library.
4. Right-click Task Scheduler Library > Create Task.
![image](https://user-images.githubusercontent.com/98122529/212526478-7ba63af9-d982-4cc0-ae26-3aabe5052fae.png)

6. Under the General Tab enter the task name - CloverTask - donotdelete and make sure the items are like the screenshot -
![image](https://user-images.githubusercontent.com/98122529/212526576-13d105b2-e7ca-46d8-977d-b8b3e6bc80cf.png)

8. Go to the Triggers tab. Click New, and then select At Startup.
![image](https://user-images.githubusercontent.com/98122529/212526608-99a9265e-cddc-479c-a50f-77b8765b0ce8.png)
![image](https://user-images.githubusercontent.com/98122529/212526759-a8fbbee2-38d9-41db-a835-193a1279dd6f.png)

10. Under Actions, click New. Enter this on the Program / Script - C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

11. Enter this for Add Arguments - -executionpolicy bypass -file C:\1Clover-tools\CloverTask.ps1

This is how it should look like -
![image](https://user-images.githubusercontent.com/98122529/212526707-18ad8337-900b-4348-89c0-e68feaf16cd3.png)
![image](https://user-images.githubusercontent.com/98122529/212526771-d97fe813-58c3-46b6-9aea-f31dc7baad37.png)


12. Click the Conditions tab and uncheck everything
![image](https://user-images.githubusercontent.com/98122529/212526738-732f0d8b-e987-458b-a43f-20b98fcacb71.png)

13. Once everything is confirmed to be correct press OK.
14. Follow the rest of the video - right-click CloverTask and select RUN.
15. Go to C:\1Clover-tools and open the status.txt file
16. Compare the Clover GUI and bootsequence should have the same information.
17. Reboot!

**Comment by Kindgentlemanthatisntkind** [comment]
Nice! Thanks a lot for your time and patience:) I restarted windows and it worked! Have a great day lad (btw I already had 1Clover-tools installed luckily but when I tried to create a folder(C:/1Clover-tools) it said that I can't use : or / when creating a folder. Maybe you just ment to make it in the c drive but I'm just making sure Incase you don't and people walk into this problem in the future as well!)

**Comment by ryanrudolfoba** [comment]
> 

No worries! Yes I meant C: drive. I'm glad its working for you now.

**Comment by ryanrudolfoba** [comment]
Solution - manually create the Scheduled Task

**Comment by ryanrudolfoba** [comment]
digging further the issue happens when there are "spaces" in the folder / directory names. 
i've since rewritten the Windows script to accomodate this.
